### ISSUE TITLE
relative imports

### ISSUE THREAD

**Issue by jakevdp** [mmp2/megaman#14]
We should try to use relative imports within the package; e.g. in ``isomap.py`` use
```python
from ..utils.eigendecomp import eigen_decomposition
```
rather than
```python
from Mmani.utils.eigendecomp import eigen_decomposition
```
The latter can bring up weird issues at times.

**Comment by jakevdp** [comment]
@jmcq89 – let me know if these kinds of things are changes you'd like me to make (and submit a PR). I don't want to conflict with other work you might be doing on the code.

**Comment by jmcq89** [comment]
If you have time that would be great Jake. I'll mostly be working on getting a good example embedding with Word2vec.

**Comment by jakevdp** [comment]
Great - will do. I'm also working on getting the Astro data together asap as well

**Comment by jakevdp** [comment]
Done in https://github.com/mmp2/megaman/commit/78cac011d6327dd4fed51e3add2caa8d5a84b45a
