### ISSUE TITLE
What is this file: ``megaman/utils/graph_testing.py``?

### ISSUE THREAD

**Issue by jakevdp** [mmp2/megaman#16]
I'm not sure whether this was supposed to be in the repo. Maybe @jmcq89 knows?

**Comment by jmcq89** [comment]
This can be removed. I wanted to confirm the scipy and sklearn methods agree -- they do.

**Comment by jakevdp** [comment]
Great – thanks!

**Comment by jakevdp** [comment]
Is that something you'd like to make into a unit test, or was it a one-off thing?

**Comment by jmcq89** [comment]
That's a one-off thing. I was removing the dependency on Sklearn and using the scipy function but I wanted to confirm we'd get the same answer. Since we do it doesn't need to be unit-tested since this is done in scipy itself -- it's the gaph_shortest_path function which Isomap uses.

**Comment by jakevdp** [comment]
got it
