### ISSUE TITLE
More generalized ``distance_matrix()``?

### ISSUE THREAD

**Issue by jakevdp** [mmp2/megaman#22]
Reading through the code, it seems we could benefit greatly from a more generalized ``distance_matrix()`` function, with this functionality passed along to each estimator. I'd imagine a call signature something like this:

```python
def distance_matrix(X, method='auto', type='radius', **kwargs):
    ...
```

- If method is ``pyflann``, then the user can either pass a pre-built flann index as a keyword argument, or leave it out and have it generated automatically
- Simiar for method=``cyflann``
- if type is ``radius`` then the user should pass a radius as a keyword argument
- if type is ``knn`` then the user should pass an integer number of neighbors as a keyword argument.

**Comment by jakevdp** [comment]
Another way we might think about this: create a ``Geometry`` base class which does all the common functions (computation of

**Comment by jakevdp** [comment]
Another thought: it would be nice to make this extensible (so e.g. someone could easily plug-in another approximate KNN algorithm) and also make it possible to easily tweak the FLANN settings.

We'll have to think about how to best do this.

**Comment by jmcq89** [comment]
Thanks for doing this Jake. The package could definitely use this "code review" from different eyes than mine.

**Comment by mmp2** [comment]
Jake, I want to second James in thanking you for the care you are putting
into this software. It will be something to be proud of!

Marina

**Comment by jakevdp** [comment]
See #23

**Comment by jmcq89** [comment]
re-factor done.
