### ISSUE TITLE
TODO: Add citation information to README & docs once arXiv paper is posted

### ISSUE THREAD

**Issue by jakevdp** [mmp2/megaman#34]

**Comment by jmcq89** [comment]
MLOSS submission: http://jmlr.org/mloss/mloss-info.html

We also need to write:

"A cover letter stating that the submission is intended for the machine learning open source software section, the open source license the software is released under, the web address of the project, and the software version to be reviewed."

Other checklist things
- Ensure the submitted code compiles and runs on all your supported platforms.

Should be ok here.
- Ensure the licensing terms of all included components comply with the open source definition and are clearly stated in the source package and mentioned in each source file.

Does our LICENSE file take care of this? Make sure that the license is mentioned in each file
- Ensure the source package contains no extra files, such as version control system files or '._' property files. (Remember that some of these may not be visible on your own platform.)

Githup download Zip should do this right?

**Comment by jakevdp** [comment]
> Does our LICENSE file take care of this? Make sure that the license is mentioned in each file

Yes – we'll have to manually add a comment in each file

> Github download Zip should do this right?

Yes, as long as we've not committed any of these temporary files!

**Comment by mmp2** [comment]
The arxiv paper is posted. Should we not include the reference and close the issue? or wait until JMLR paper is out?

http://arxiv.org/pdf/1603.02763.pdf
