### ISSUE TITLE
Any easy way to apply learned mapping on different set of points?

### ISSUE THREAD

**Issue by MInner** [mmp2/megaman#74]
Thanks for a great library!

I wonder if there is an easy way to perform `transform()` only? I have sets of points `A` and `B_t for t in [0..T]` and I want to plot how `B` changes over time, so I was wondering if I could train an embedding on `A` and see `B_t` projections onto `A's` coordinates.

Thank you!

**Comment by mmp2** [comment]
yes, nystrom extension does this. in utils/

best, MMP

**Comment by jmcq89** [comment]
If you're using spectral_embedding I have implemented a predict function:

https://github.com/mmp2/megaman/blob/master/megaman/embedding/spectral_embedding.py#L407
