### ISSUE TITLE
Cyflann - ValueError: Buffer dtype mismatch, expected 'double' but got 'float'

### ISSUE THREAD

**Issue by SnowRipple** [mmp2/megaman#77]
Hi there!
     I am trying to use Spectral embedding "predict" function. I have some training data I want to use to create embedding and some testing data I would like to project onto this new embedding. 

` radius = 0.5 
    adjacency_method = 'cyflann'
    adjacency_kwds = {'radius':radius}
    affinity_method = 'gaussian'
    affinity_kwds = {'radius':radius}
    laplacian_method = 'symmetricnormalized'
    laplacian_kwds = {'scaling_epps':radius}
    color = 'b' `

 `geom = Geometry(adjacency_kwds=adjacency_kwds,
                    affinity_kwds=affinity_kwds)
dr_technique = SpectralEmbedding(n_components=target_dim, 
                                     eigen_solver='auto',geom=geom, drop_first=False) # use 3 for spectral
   dr_technique.fit(data)
  final_array = dr_technique.predict(data)`
Produces:

` File "/usr/local/lib/python2.7/dist-packages/megaman/embedding/spectral_embedding.py", line 428, in predict
    X_test,adjacency_kwds)
  File "/usr/local/lib/python2.7/dist-packages/megaman/geometry/complete_adjacency_matrix.py", line 12, in complete_adjacency_matrix
    train_index = Cyflann.build_index(Xtrain)
  File "/usr/local/lib/python2.7/dist-packages/megaman/geometry/adjacency.py", line 113, in build_index
    return self._get_built_index(X)
  File "/usr/local/lib/python2.7/dist-packages/megaman/geometry/adjacency.py", line 105, in _get_built_index
    **(self.cyflann_kwds or {}))
  File "index.pyx", line 18, in megaman.geometry.cyflann.index.Index.__cinit__
ValueError: Buffer dtype mismatch, expected 'double' but got 'float'`

What am I doing wrong? 

Can projecting test data on already created embedding be done using other techniques in the megaman package like LLE, LTSA or Isomap?

Many Thanks!

**Comment by SnowRipple** [comment]
ok, casting data to numpy float64 seems to fix the issue.

I will close this issuse but can someone answer my question considering projecting test data using other techniques please?

**Comment by jmcq89** [comment]
Hi Piotr,

Thanks for catching this we will make sure the numpy float64 bug is
addressed in the next release.

Currently, due to the way that the Nystrom Extension works, we only have
Spectral Embedding set up for .predict() as the other methods would require
significantly more work. It is future work for megaman to add scalable
.predict() methods for the other embeddings. If there is one in particular
that interests you most we might be able to put that specific method higher
on the pipeline.

Cheers,
James

**Comment by SnowRipple** [comment]
Thanks James! 
It's great news that such improvements are on the agenda!

Personally I was wondering if it is even possible to provide "predict" method for all other methods.E.g. in LLE don't you have to recalculate the whole embedding for "out-of-sample" data?

Anyways if you could give LLE higher priority that would be awesome!

Big Fan of your work guys!:)
