### ISSUE TITLE
Megaman benchmarks

### ISSUE THREAD

**Issue by mattare2** [mmp2/megaman#79]
I'm looking at applying megaman to cluster on a large set of sentence embeddings, but I was hoping for more detail than an ordinal ranking of the algorithms.  Is there a source that has benchmarked times on the different megaman algorithms? 

Thanks,

Andrew

**Comment by mmp2** [comment]
Not sure what you mean by "ordinal ranking of the algorithms"?

We have benchmarks for manifold embeddings but not clustering. Spectral clustering would take about as much as spectral_embedding.

Hope this helps,

Marina Meila

Andrew M writes:
 > 
 > I'm looking at applying megaman to cluster on a large set of sentence embeddings, but I was hoping for more detail than an ordinal ranking of the algorithms.  Is there a source that has benchmarked times on the different megaman algorithms? 
 > 
 > Thanks,
 > 
 > Andrew
 > 
 > -- 
 > You are receiving this because you are subscribed to this thread.
 > Reply to this email directly or view it on GitHub:
 > https://github.com/mmp2/megaman/issues/79
-- 
_______________________________________________________________________
      Marina Meila
  ,_ o  ACMS Director         University of Washington       Box  354322
 / //\   Professor of Statistics                  Seattle WA 98195-4322
__\>>_|__ mmp@stat.washington.edu               phone: 206-543-8484
   \\,     www.stat.washington.edu/mmp      office: Padelford B-321
_______________________________________________________________________

**Comment by mattare2** [comment]
Sorry--my explanation wasn't clear.  

I'm using megaman for dimensionality reduction, prior to clustering.  

I'm looking at the tutorial notebook, which provides an ordered list of how well the algorithms scale from best to worst, but I was hoping for more detailed benchmarks on the embedding algorithms.   Where can I find those?

Thank you,

Andrew

**Comment by jmcq89** [comment]
We did some rough benchmarking in an earlier version of megaman here: https://github.com/mmp2/megaman/tree/1c8e9010d5e03e8e0c257885209e866ad30771c5/benchmarks

Ultimately, however, when the data set becomes larger than say 100,000 points Spectral Embedding vastly out-scales the other methods. Since our data sets were all significantly larger than 100K we dedicated most of the time to benchmarking and evaluating Spectral Embedding as in the JMLR paper.

**Comment by mattare2** [comment]
Somehow I managed to completely miss the folder clearly marked "Benchmarks".

Very helpful, thank you.

**Comment by jmcq89** [comment]
You didn't miss the folder, that's from an old commit -- it doesn't exist in live anymore :) 

If you're interested, it would be fantastic to do a more formal benchmarking of the methods!

**Comment by mattare2** [comment]
I'll put this on my to-do list, but unfortunately it's cluttered with so many other things already.
