### ISSUE TITLE
cannot import megaman.geometry

### ISSUE THREAD

**Issue by hainguyenct** [mmp2/megaman#83]
I installed megaman without errors
```
megaman$ python setup.py install
Cythonizing sources
megaman/__check_build/_check_build.pyx has not changed
megaman/geometry/cyflann/index.pyx has not changed
Compiling FLANN with FLANN_ROOT=/anaconda2
running install
running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_src
build_src
building extension "megaman.__check_build._check_build" sources
building extension "megaman.geometry/cyflann.index" sources
building data_files sources
build_src: building npy-pkg config files
running build_py
running build_ext
customize UnixCCompiler
customize UnixCCompiler using build_ext
customize UnixCCompiler
customize UnixCCompiler using build_ext
running install_lib
running install_data
running install_egg_info
Removing /anaconda2/lib/python2.7/site-packages/megaman-0.3.dev0-py2.7.egg-info
Writing /anaconda2/lib/python2.7/site-packages/megaman-0.3.dev0-py2.7.egg-info
running install_clib
customize UnixCCompiler
```

However, I received errors as below when call megaman:
```
from megaman.geometry import Geometry
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "megaman/__init__.py", line 7, in <module>
    from . import __check_build
  File "megaman/__check_build/__init__.py", line 56, in <module>
    raise_build_error(e)
  File "megaman/__check_build/__init__.py", line 51, in raise_build_error
    msg=msg))
ImportError: No module named _check_build
___________________________________________________________________________
Contents of megaman/__check_build:
__init__.py               __init__.pyc              _check_build.c
_check_build.pyx          setup.py                  setup.pyc
___________________________________________________________________________
It seems that megaman has not been built correctly.

If you have installed megaman from source, please do not forget
to build the package before using it: run `python setup.py install`
in the source directory.

It appears that you are importing a local megaman source tree.
Please either use an inplace install or try from another location.
```
Anyone could help me, please. Thank you.

**Comment by yuchaz** [comment]
It seems like you tried to import megaman in the build folder. (Correct me if I was wrong.) 
Could you try import megaman in different directories?

Python interpreter will first find the modules named `megaman` in current directory, if not found, it will find in installed modules. After running `python setup.py install`, `megaman` will be built and moved to the packages directories. If you import `megaman` in the built folder,  modules in current directories (which is not yet built) will have higher priority in module import and therefore the built version will not be imported.

[Official documentations](https://docs.python.org/2/tutorial/modules.html#the-module-search-path)
> When a module named `spam` is imported, the interpreter first searches for a built-in module with that name. If not found, it then searches for a file named `spam.py` in a list of directories given by the variable `sys.path`. `sys.path` is initialized from these locations:
>1. The directory containing the input script (or the current directory when no file is specified).
>1. PYTHONPATH (a list of directory names, with the same syntax as the shell variable PATH).
>1. The installation-dependent default.

**Comment by hainguyenct** [comment]
Yes, that is it. Now, it works! Thank you.
